version: '3.7'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-control-webapp
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000
